wait for the deployment to be rolled out before continuing

diff --git a/addons/velero/template/testgrid/k8s-docker.yaml b/addons/velero/template/testgrid/k8s-docker.yaml
--- a/addons/velero/template/testgrid/k8s-docker.yaml
+++ b/addons/velero/template/testgrid/k8s-docker.yaml
@@ -1,24 +1,24 @@
-- name: "Velero Minimal"
-  cpu: 6
-  installerSpec:
-    kubernetes:
-      version: "1.27.x"
-    flannel:
-      version: latest
-    rook:
-      version: 1.12.x
-    containerd:
-      version: "latest"
-    kotsadm:
-      version: latest
-    velero:
-      version: "__testver__"
-      s3Override: "__testdist__"
-  postInstallScript: |
-    source /opt/kurl-testgrid/testhelpers.sh
-    install_and_customize_kurl_integration_test_application
-    timeout 5m kubectl kots backup
-    timeout 5m kubectl kots backup ls
+#- name: "Velero Minimal"
+#  cpu: 6
+#  installerSpec:
+#    kubernetes:
+#      version: "1.27.x"
+#    flannel:
+#      version: latest
+#    rook:
+#      version: 1.12.x
+#    containerd:
+#      version: "latest"
+#    kotsadm:
+#      version: latest
+#    velero:
+#      version: "__testver__"
+#      s3Override: "__testdist__"
+#  postInstallScript: |
+#    source /opt/kurl-testgrid/testhelpers.sh
+#    install_and_customize_kurl_integration_test_application
+#    timeout 5m kubectl kots backup
+#    timeout 5m kubectl kots backup ls
 #- name: "Velero Minimal Airgap"
 #  cpu: 6
 #  airgap: true
@@ -134,48 +134,48 @@
 #    timeout 5m kubectl kots backup
 #    timeout 5m kubectl kots backup ls
 #
-#- name: "Velero remove restic"
-#  cpu: 8
-#  installerSpec:
-#    kubernetes:
-#      version: "1.27.x"
-#    flannel:
-#      version: latest
-#    rook:
-#      version: 1.12.x
-#    containerd:
-#      version: "latest"
-#    kotsadm:
-#      version: latest
-#    velero:
-#      version: "1.9.x"
-#  upgradeSpec:
-#    kubernetes:
-#      version: "1.27.x"
-#    flannel:
-#      version: latest
-#    rook:
-#      version: 1.12.x
-#    containerd:
-#      version: "latest"
-#    kotsadm:
-#      version: latest
-#    velero:
-#      version: "__testver__"
-#      s3Override: "__testdist__"
-#  postInstallScript: |
-#    source /opt/kurl-testgrid/testhelpers.sh
-#    install_and_customize_kurl_integration_test_application
-#    timeout 5m kubectl kots backup
-#    timeout 5m kubectl kots backup ls
-#  postUpgradeScript: |
-#    source /opt/kurl-testgrid/testhelpers.sh
-#    kubectl get pods -n velero
-#    timeout 5m kubectl kots backup
-#    timeout 5m kubectl kots backup ls
-#    # if restic pods are still running, fail the test
-#    if kubectl get pods -n velero | grep restic; then
-#      echo "Restic pods still running after upgrade"
-#      exit 1
-#    fi
-#
+- name: "Velero remove restic"
+  cpu: 8
+  installerSpec:
+    kubernetes:
+      version: "1.27.x"
+    flannel:
+      version: latest
+    rook:
+      version: 1.12.x
+    containerd:
+      version: "latest"
+    kotsadm:
+      version: latest
+    velero:
+      version: "1.9.x"
+  upgradeSpec:
+    kubernetes:
+      version: "1.27.x"
+    flannel:
+      version: latest
+    rook:
+      version: 1.12.x
+    containerd:
+      version: "latest"
+    kotsadm:
+      version: latest
+    velero:
+      version: "__testver__"
+      s3Override: "__testdist__"
+  postInstallScript: |
+    source /opt/kurl-testgrid/testhelpers.sh
+    install_and_customize_kurl_integration_test_application
+    timeout 5m kubectl kots backup
+    timeout 5m kubectl kots backup ls
+  postUpgradeScript: |
+    source /opt/kurl-testgrid/testhelpers.sh
+    kubectl get pods -n velero
+    timeout 5m kubectl kots backup
+    timeout 5m kubectl kots backup ls
+    # if restic pods are still running, fail the test
+    if kubectl get pods -n velero | grep restic; then
+      echo "Restic pods still running after upgrade"
+      exit 1
+    fi
+
