Failed package build should not fail entire batch

diff --git a/.github/workflows/cron-rebuild-packages-prod.yaml b/.github/workflows/cron-rebuild-packages-prod.yaml
--- a/.github/workflows/cron-rebuild-packages-prod.yaml
+++ b/.github/workflows/cron-rebuild-packages-prod.yaml
@@ -45,10 +45,18 @@ jobs:
           git checkout $tag
           export KURL_UTIL_IMAGE=replicated/kurl-util:$tag # required if this is the common package
 
+          failed_pkgs=
+
           for PKG in ${BATCH}; do
             if [ -z "$PKG" ]; then continue; fi
 
+            set +e
             make dist/$PKG
+            status="$?"
+            set -e
+            if [ "${status}" != "0" ]; then
+              failed_pkgs="${failed_pkgs}${PKG} "
+            fi
 
             MD5="$(openssl md5 -binary dist/$PKG | base64)"
             GITSHA="$(git rev-parse HEAD)"
@@ -57,3 +65,8 @@ jobs:
             aws s3 cp s3://kurl-sh/dist/${tag}/$PKG s3://kurl-sh/dist/$PKG \
               --metadata md5="${MD5}",gitsha="${GITSHA}"
           done
+
+          if [ -n "${failed_pkgs}" ]; then
+            echo "Failed to build packages ${failed_pkgs}"
+            exit 1
+          fi
diff --git a/.github/workflows/cron-rebuild-packages-staging.yaml b/.github/workflows/cron-rebuild-packages-staging.yaml
--- a/.github/workflows/cron-rebuild-packages-staging.yaml
+++ b/.github/workflows/cron-rebuild-packages-staging.yaml
@@ -46,10 +46,18 @@ jobs:
           export VERSION_TAG=$(git tag | grep '^v20' | sort | tail -1)-dirty
           export KURL_UTIL_IMAGE=replicated/kurl-util:${VERSION_TAG}
 
+          failed_pkgs=
+
           for PKG in ${BATCH}; do
             if [ -z "$PKG" ]; then continue; fi
 
+            set +e
             make dist/$PKG
+            status="$?"
+            set -e
+            if [ "${status}" != "0" ]; then
+              failed_pkgs="${failed_pkgs}${PKG} "
+            fi
 
             MD5="$(openssl md5 -binary dist/$PKG | base64)"
             GITSHA="$(git rev-parse HEAD)"
@@ -58,3 +66,8 @@ jobs:
             aws s3 cp s3://kurl-sh/staging/${VERSION_TAG}/$PKG s3://kurl-sh/staging/$PKG \
               --metadata md5="${MD5}",gitsha="${GITSHA}"
           done
+
+          if [ -n "${failed_pkgs}" ]; then
+            echo "Failed to build packages ${failed_pkgs}"
+            exit 1
+          fi
