ci: Copy Staging Release for a given Tag when Deploying to Prod (#3867)
* WIP: Copy stage release assets when promoting to prod

* Add verify testgrid result job

* Add more details to verify testgrid job

* Verify testgrid run prior to release

* Fix api call to get run details

* Copy correct staging directory to prod

* create release note after assets have been copied to prod

* Build common and kur-utils packages and exclude from s3 copy

* Update .github/workflows/deploy-prod.yaml

Co-authored-by: Andrew Lavery <laverya@umich.edu>

* Change tag to commit

Co-authored-by: Andrew Lavery <laverya@umich.edu>

Co-authored-by: Andrew Lavery <laverya@umich.edu>

diff --git a/.github/workflows/deploy-prod.yaml b/.github/workflows/deploy-prod.yaml
--- a/.github/workflows/deploy-prod.yaml
+++ b/.github/workflows/deploy-prod.yaml
@@ -17,24 +17,6 @@ jobs:
         export VERSION_TAG=$GITHUB_REF_NAME
         ./bin/verify-tag.sh "${VERSION_TAG}"
 
-  generate-kurl-release-notes-pr:
-    runs-on: ubuntu-20.04
-    needs:
-    - verify-tag
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Generate kURL Release Notes PR
-      env:
-        GH_PAT: ${{ secrets.AUTOMATED_PR_GH_PAT }}
-      run: |
-        export VERSION_TAG=$GITHUB_REF_NAME
-        curl -H "Authorization: token $GH_PAT" \
-          -H 'Accept: application/json' \
-          -d "{\"event_type\": \"kubernetes-installer-release-notes\", \"client_payload\": {\"version\": \"${VERSION_TAG}\" }}" \
-          "https://api.github.com/repos/replicatedhq/replicated-docs/dispatches"
-
   kurl-util-image:
     runs-on: ubuntu-20.04
     needs:
@@ -52,7 +34,7 @@ jobs:
         docker tag replicated/kurl-util:${VERSION_TAG} replicated/kurl-util
         docker push replicated/kurl-util
 
-  build-matrix:
+  build-go-bins-matrix:
     runs-on: ubuntu-20.04
     needs:
     - kurl-util-image
@@ -67,13 +49,14 @@ jobs:
         export VERSION_TAG=$GITHUB_REF_NAME
         export KURL_UTIL_IMAGE=replicated/kurl-util:${VERSION_TAG}
         export KURL_BIN_UTILS_FILE=kurl-bin-utils-${VERSION_TAG}.tar.gz
+        export FILTER_GO_BINS_ONLY="1"
         OUTPUT=`bin/list-all-packages-actions-matrix.sh "${{ github.event.inputs.index }}"`
         echo "::set-output name=matrix::$OUTPUT"
 
   build-upload-packages:
     runs-on: ubuntu-20.04
     needs:
-    - build-matrix
+    - build-go-bins-matrix
     strategy:
       matrix: ${{fromJSON(needs.build-matrix.outputs.matrix)}}
       fail-fast: false
@@ -98,7 +81,6 @@ jobs:
         export VERSION_TAG=$GITHUB_REF_NAME
         export KURL_UTIL_IMAGE=replicated/kurl-util:${VERSION_TAG}
         export KURL_BIN_UTILS_FILE=kurl-bin-utils-${VERSION_TAG}.tar.gz
-
         bin/upload-dist-versioned.sh "${{ matrix.batch }}"
       env:
         S3_BUCKET: kurl-sh
@@ -106,30 +88,89 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
         AWS_REGION: "us-east-1"
 
-  build-addons:
+  get-staging-release:
     runs-on: ubuntu-20.04
     needs:
-    - kurl-util-image
+    - verify-tag
+    outputs:
+      staging_release: ${{ steps.get_staging_release.outputs.staging_release }}
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-node@v3
-      with:
-        node-version: '14'
-    - run: npm install
-    - run: |
-        export VERSION_TAG=$GITHUB_REF_NAME
-        make generate-addons
+    - name: find corresponding staging release for commit
+      id: get_staging_release
+      run: |
+        version_commit="$(git rev-list "${GITHUB_REF_NAME}" -n 1 | xargs git rev-parse --short)"
+        staging_release_dir="$(aws s3 ls s3://"${S3_BUCKET}/${STAGING_PREFIX}/" | grep "${version_commit}" | awk '{print $2}')"
+        if [ -z "${staging_release_dir}" ]; then
+            echo "Could not find staging release for commit ${GITHUB_REF_NAME} (${version_commit})"
+            exit 1
+        fi
+        echo "staging_release=${staging_release_dir%/}" >> $GITHUB_OUTPUT
       env:
         S3_BUCKET: kurl-sh
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: "us-east-1"
-        DIST_FOLDER: "dist"
+        AWS_REGION: "us-east-1"
+        STAGING_PREFIX: "staging"
+
+  verify-staging-release-testgrid-result:
+    runs-on: ubuntu-20.04
+    needs:
+    - verify-tag
+    - get-staging-release
+    steps:
+    - name: Verify Testgrid Run
+      run: |
+        ./bin/verify-testgrid-run.sh
+      env:
+        STAGING_RELEASE: ${{ needs.get-staging-release.outputs.staging_release }}
+
+  copy-staging-release-to-prod:
+    runs-on: ubuntu-20.04
+    needs:
+     - verify-staging-release-testgrid-result
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+
+    - name: Copy Staging Release to Prod
+      run: |
+        export VERSION_TAG=$GITHUB_REF_NAME
+        . bin/upload-dist-versioned.sh
+        copy_staging_release_to_dist
+      env:
+        S3_BUCKET: kurl-sh
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
+        AWS_REGION: "us-east-1"
+        STAGING_RELEASE: ${{ needs.get-staging-release.outputs.staging_release }}
+
+  generate-kurl-release-notes-pr:
+    runs-on: ubuntu-20.04
+    needs:
+    - verify-tag
+    - get-staging-release
+    - copy-staging-release-to-prod
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v2
+
+    - name: Generate kURL Release Notes PR
+      env:
+        GH_PAT: ${{ secrets.AUTOMATED_PR_GH_PAT }}
+      run: |
+        export VERSION_TAG=$GITHUB_REF_NAME
+        curl -H "Authorization: token $GH_PAT" \
+          -H 'Accept: application/json' \
+          -d "{\"event_type\": \"kubernetes-installer-release-notes\", \"client_payload\": {\"version\": \"${VERSION_TAG}\" }}" \
+          "https://api.github.com/repos/replicatedhq/replicated-docs/dispatches"
+
 
   github-release:
     runs-on: ubuntu-20.04
     needs:
     - kurl-util-image
+    - copy-staging-release-to-prod
     steps:
     - name: Checkout
       uses: actions/checkout@v3
@@ -212,8 +253,7 @@ jobs:
   set-current-version:
     runs-on: ubuntu-20.04
     needs:
-    - build-addons
-    - build-upload-packages
+    - copy-staging-release-to-prod
     steps:
     - name: Set VERSION file in s3
       run: |
